# Generated by Django 4.0.3 on 2022-03-16 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='publisher_date',
            field=models.DateField(verbose_name='Fecha publicación'),
        ),
    ]
