# Generated by Django 4.0.3 on 2022-03-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_author_created_date_alter_author_publisher_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='publisher_date',
        ),
    ]
